### ISSUE TITLE
Image saving error

### ISSUE THREAD

**Issue by Wemmons831** [lucidrains/big-sleep#97]
Hello I am using Big-Sleep straight out of command line on windows with no extra flags but for some reason when ever I get to image update 2 or 5 (most times 2) it errors out giving the error `OSError: [Errno 22] Invalid argument:` I couldn't find any fix that would work in this situation. Any and all help as to solving this error is greatly appreciated

**Comment by wolfgangmeyers** [comment]
I haven't seen that particular error, but I know that if you are viewing the image in windows explorer, each time the image updates windows will open the image briefly in order to update the thumbnail. Sometimes this can prevent the process from saving the image due to the file not being available for writing. If you set open_folder to False, it might help.

**Comment by Wemmons831** [comment]
> I haven't seen that particular error, but I know that if you are viewing the image in windows explorer, each time the image updates windows will open the image briefly in order to update the thumbnail. Sometimes this can prevent the process from saving the image due to the file not being available for writing. If you set open_folder to False, it might help.

Yep From my experience having file explorer open doesn't effect it but having the photos app open does
